language: go

go:
- "1.11.x"
- "1.12.x"

branches:
  only:
  - master
  - develop

services:
  - mysql
  - redis-server
  - elasticsearch

env:
- GO111MODULE=on

install:
- go mod download


before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- find . -name "*.go" | xargs gofmt -w
- git diff --exit-code

script:
- GOARCH=386 go test -v ./...
- GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)

# true表示不执行任何脚本，状态直接设为成功。
#  before_install：install 阶段之前执行
#  before_script：script 阶段之前执行
#  after_failure：script 阶段失败时执行
#  after_success：script 阶段成功时执行
#  before_deploy：deploy 步骤之前执行
#  after_deploy：deploy 步骤之后执行
#  after_script：script 阶段之后执行