# 文档http://www.ruanyifeng.com/blog/2017/12/travis_ci_tutorial.html
language: go

go:
- "1.11.x"
- "1.12.x"

branches:
  only:
  - master
  - develop

cache:
  directories:
    - $GOPATH/pkg/mod/

services:
  - mysql
  - redis-server
  - elasticsearch

env:
- GO111MODULE=on

install:
- go mod download


before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- find . -name "*.go" | xargs gofmt -w
- git diff --name-only --exit-code || echo -e "\033[31mPlease format above files\033[0m" && exit 1

script:
- GOARCH=386 go test -v ./... || echo "test Failed" && exit 1
- GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)