# 文档 http://www.ruanyifeng.com/blog/2017/12/travis_ci_tutorial.html
language: go

go:
- "1.13.x"

branches:
  only:
  - master
  - develop

services:
  - mysql
  - redis-server
  - elasticsearch

env:
- GO111MODULE=on

install:
- go mod download


before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- find . -name "*.go" | xargs gofmt -w
- git diff --name-only --exit-code || exit 1

script:
- GOARCH=386 go test -v ./... || exit 0
- GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)